apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kes-example
  name: kes-example
  labels:
    app: kes-example
spec:
  replicas: 1 
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kes-example
  template:
    metadata:
      annotations:
      labels:
        app: kes-example
    spec:
      containers:
        - name: server
          image: vietanhs0817/nginx-demo:v3.0
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
