apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  namespace: kes-example
  name: kes-example
spec:
  backendType: vault
  kvVersion: 2
  data:
    - name: password 
      key: data/data/example/secrets
      property: password 
    - name: cert.p12
      key: data/data/example/files
      property: cert.p12
      isBinary: true
---
# docker config json
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  namespace: kes-example
  name: regcred
spec:
  backendType: vault
  template:
    type: kubernetes.io/dockerconfigjson
  kvVersion: 2
  data:
    - name: .dockerconfigjson 
      key: data/data/example/docker
      property: credentials